In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
base = pd.read_csv("natural_disasters_2024.csv")

In [ ]:
base.head(5)

,Disaster_ID,Disaster_Type,Location,Magnitude,Date,Fatalities,Economic_Loss($)
0,1,Wildfire,Brazil,6.267393,2024-01-01 00:00:00,9706,6.509790e+08
1,2,Hurricane,Indonesia,6.649358,2024-01-01 01:00:00,2233,5.538357e+08
2,3,Tornado,China,9.724366,2024-01-01 02:00:00,478,6.910998e+07
3,4,Flood,India,1.702505,2024-01-01 03:00:00,2867,8.474880e+08
4,5,Flood,Brazil,7.917748,2024-01-01 04:00:00,776,6.449297e+08

In [ ]:
base.describe()

       Disaster_ID     Magnitude    Fatalities  Economic_Loss($)
count  10000.00000  10000.000000  10000.000000      1.000000e+04
mean    5000.50000      5.559173   4984.928900      5.049752e+08
std     2886.89568      2.619304   2900.114029      2.861325e+08
min        1.00000      1.000656      0.000000      1.036597e+06
25%     2500.75000      3.263217   2481.750000      2.636352e+08
50%     5000.50000      5.589578   4947.000000      5.078407e+08
75%     7500.25000      7.829268   7511.250000      7.527256e+08
max    10000.00000      9.999671   9999.000000      9.998528e+08

## Separando em Treino e Teste

In [ ]:
## 80% dos dados para treino
train = base.sample(frac=0.8, random_state=42)

#teste do restante dos 20% de dados
test = base.drop(train.index)

print(train.describe(include="all"))
print("--------")
print(test.describe(include="all"))

         Disaster_ID Disaster_Type Location    Magnitude                 Date  \
count    8000.000000          8000     8000  8000.000000                 8000
unique           NaN             5        6          NaN                 8000
top              NaN    Earthquake   Brazil          NaN  2024-09-17 12:00:00
freq             NaN          1632     1420          NaN                    1
mean     4989.523375           NaN      NaN     5.534683                  NaN
std      2887.824119           NaN      NaN     2.614892                  NaN
min         1.000000           NaN      NaN     1.000656                  NaN
25%      2481.750000           NaN      NaN     3.239857                  NaN
50%      4979.500000           NaN      NaN     5.507489                  NaN
75%      7500.250000           NaN      NaN     7.815497                  NaN
max     10000.000000           NaN      NaN     9.999671                  NaN

         Fatalities  Economic_Loss($)
count   8000.000000      8.000000e+03
unique          NaN               NaN
top             NaN               NaN
freq            NaN               NaN
mean    4974.710875      5.042245e+08
std     2894.010900      2.864435e+08
min        0.000000      1.036597e+06
25%     2488.250000      2.613780e+08
50%     4921.500000      5.067632e+08
75%     7480.500000      7.520808e+08
max     9999.000000      9.998528e+08
--------
        Disaster_ID Disaster_Type Location    Magnitude                 Date  \
count   2000.000000          2000     2000  2000.000000                 2000
unique          NaN             5        6          NaN                 2000
top             NaN         Flood      USA          NaN  2024-01-01 01:00:00
freq            NaN           429      355          NaN                    1
mean    5044.406500           NaN      NaN     5.657132                  NaN
std     2883.482435           NaN      NaN     2.635259                  NaN
min        2.000000           NaN      NaN     1.004596                  NaN
25%     2560.500000           NaN      NaN     3.346878                  NaN
50%     5105.500000           NaN      NaN     5.833962                  NaN
75%     7498.750000           NaN      NaN     7.882273                  NaN
max     9998.000000           NaN      NaN     9.993792                  NaN

         Fatalities  Economic_Loss($)
count   2000.000000      2.000000e+03
unique          NaN               NaN
top             NaN               NaN
freq            NaN               NaN
mean    5025.801000      5.079781e+08
std     2924.770393      2.849367e+08
min        0.000000      1.419696e+06
25%     2463.000000      2.688909e+08
50%     5068.500000      5.134232e+08
75%     7546.500000      7.550598e+08
max     9991.000000      9.991659e+08

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8000 entries, 6252 to 6907
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Disaster_ID       8000 non-null   int64
 1   Disaster_Type     8000 non-null   object
 2   Location          8000 non-null   object
 3   Magnitude         8000 non-null   float64
 4   Date              8000 non-null   object
 5   Fatalities        8000 non-null   int64
 6   Economic_Loss($)  8000 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 500.0+ KB

In [ ]:
# pra saber quantos atributos unicos eu tenho na coluna do tipo de desastres
base['Disaster_Type'].unique()

array(['Wildfire', 'Hurricane', 'Tornado', 'Flood', 'Earthquake'],
      dtype=object)

### **Gerando valores numéricos**

Para Disaster Type, utilizamos a estratégica **OneHotEncoder**: Dessa forma, conseguimos transformar os atributos categóricos em binários (True or False; 0 or 1)

In [ ]:
# One Hot Encoder aplicado aos tipos de desastre
pd.get_dummies(train['Disaster_Type'])

      Earthquake  Flood  Hurricane  Tornado  Wildfire
6252       False  False      False    False      True
4684       False  False       True    False     False
1731       False   True      False    False     False
4742       False   True      False    False     False
4521        True  False      False    False     False
...          ...    ...        ...      ...       ...
1638       False  False      False     True     False
5891       False  False      False    False      True
7427       False  False      False     True     False
608        False  False       True    False     False
6907       False  False      False     True     False

[8000 rows x 5 columns]

O código obteve os valores (Wildfire, Hurricane, Tornado, Flood, Earthquake) da coluna Disaster Type e transformou em 5 colunas. Dessa forma, o 1 indica o tipo do desastre, e o 0 diz que não foi determinado tipo.

In [ ]:
# Aqui a gente tá adicionando as linhas e colunas dos tipos de desastre -> com a aplicação do oneHotEnconder
train = pd.concat([train, pd.get_dummies(train['Disaster_Type']).astype(int)], axis = "columns")
test = pd.concat([test, pd.get_dummies(test['Disaster_Type']).astype(int)], axis = "columns")

In [ ]:
train

,Disaster_ID,Disaster_Type,Location,Magnitude,Date,Fatalities,Economic_Loss($),Earthquake,Flood,Hurricane,Tornado,Wildfire
6252,6253,Wildfire,China,5.779710,2024-09-17 12:00:00,1800,6.561750e+08,0,0,0,0,1
4684,4685,Hurricane,Japan,8.115571,2024-07-14 04:00:00,239,7.489289e+08,0,0,1,0,0
1731,1732,Flood,Indonesia,7.679975,2024-03-13 03:00:00,9438,3.617054e+08,0,1,0,0,0
4742,4743,Flood,Japan,8.986789,2024-07-16 14:00:00,7176,6.389135e+08,0,1,0,0,0
4521,4522,Earthquake,Brazil,8.400407,2024-07-07 09:00:00,6728,4.586667e+08,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1638,1639,Tornado,Japan,5.386034,2024-03-09 06:00:00,284,8.257273e+08,0,0,0,1,0
5891,5892,Wildfire,India,6.210858,2024-09-02 11:00:00,488,6.925771e+08,0,0,0,0,1
7427,7428,Tornado,Brazil,8.399872,2024-11-05 11:00:00,483,7.696961e+08,0,0,0,1,0
608,609,Hurricane,USA,4.849663,2024-01-26 08:00:00,2247,2.863837e+08,0,0,1,0,0
6907,6908,Tornado,Japan,6.734496,2024-10-14 19:00:00,5409,1.243052e+08,0,0,0,1,0

In [ ]:
# Puxando as infos de treinamento
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8000 entries, 6252 to 6907
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Disaster_ID       8000 non-null   int64
 1   Disaster_Type     8000 non-null   object
 2   Location          8000 non-null   object
 3   Magnitude         8000 non-null   float64
 4   Date              8000 non-null   object
 5   Fatalities        8000 non-null   int64
 6   Economic_Loss($)  8000 non-null   float64
 7   Earthquake        8000 non-null   int64
 8   Flood             8000 non-null   int64
 9   Hurricane         8000 non-null   int64
 10  Tornado           8000 non-null   int64
 11  Wildfire          8000 non-null   int64
dtypes: float64(2), int64(7), object(3)
memory usage: 1.0+ MB

In [ ]:
base.Location.unique()

array(['Brazil', 'Indonesia', 'China', 'India', 'USA', 'Japan'],
      dtype=object)

In [ ]:
# Aplicando o oneHotEncoder aqui nas localizações
pd.get_dummies(train.Location)

      Brazil  China  India  Indonesia  Japan    USA
6252   False   True  False      False  False  False
4684   False  False  False      False   True  False
1731   False  False  False       True  False  False
4742   False  False  False      False   True  False
4521    True  False  False      False  False  False
...      ...    ...    ...        ...    ...    ...
1638   False  False  False      False   True  False
5891   False  False   True      False  False  False
7427    True  False  False      False  False  False
608    False  False  False      False  False   True
6907   False  False  False      False   True  False

[8000 rows x 6 columns]

In [ ]:
# Aplicando as colunas e linhas geradas pelo oneHotEncoder -> referente às localizações
train = pd.concat([train, pd.get_dummies(train.Location).astype(int)], axis = "columns")
test = pd.concat([test, pd.get_dummies(test.Location).astype(int)], axis = "columns")

In [ ]:
train

,Disaster_ID,Disaster_Type,Location,Magnitude,Date,Fatalities,Economic_Loss($),Earthquake,Flood,Hurricane,Tornado,Wildfire,Brazil,China,India,Indonesia,Japan,USA
6252,6253,Wildfire,China,5.779710,2024-09-17 12:00:00,1800,6.561750e+08,0,0,0,0,1,0,1,0,0,0,0
4684,4685,Hurricane,Japan,8.115571,2024-07-14 04:00:00,239,7.489289e+08,0,0,1,0,0,0,0,0,0,1,0
1731,1732,Flood,Indonesia,7.679975,2024-03-13 03:00:00,9438,3.617054e+08,0,1,0,0,0,0,0,0,1,0,0
4742,4743,Flood,Japan,8.986789,2024-07-16 14:00:00,7176,6.389135e+08,0,1,0,0,0,0,0,0,0,1,0
4521,4522,Earthquake,Brazil,8.400407,2024-07-07 09:00:00,6728,4.586667e+08,1,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,1639,Tornado,Japan,5.386034,2024-03-09 06:00:00,284,8.257273e+08,0,0,0,1,0,0,0,0,0,1,0
5891,5892,Wildfire,India,6.210858,2024-09-02 11:00:00,488,6.925771e+08,0,0,0,0,1,0,0,1,0,0,0
7427,7428,Tornado,Brazil,8.399872,2024-11-05 11:00:00,483,7.696961e+08,0,0,0,1,0,1,0,0,0,0,0
608,609,Hurricane,USA,4.849663,2024-01-26 08:00:00,2247,2.863837e+08,0,0,1,0,0,0,0,0,0,0,1
6907,6908,Tornado,Japan,6.734496,2024-10-14 19:00:00,5409,1.243052e+08,0,0,0,1,0,0,0,0,0,1,0

### **Organizando os dados**

**x_train** e **x_test** -> armazenam as classes preditoras (características do modelo)

**y_train** e **y_test** -> variáveis rótulos, aquilo que queremos prever

As variáveis de train, dizem respeito às classes preditoras(x_train) e as classes alvo (y_train)

E as classes test, dizem respeito ao desempenho do modelo aprós o treinamento.

In [ ]:
# Aqui relacionamos todos os atributos, ignorando apenas a data e o ID a fim de prever impactos econômicos
## Valores de treino
x_train = train.loc[ : , ["Magnitude", "Fatalities", "Earthquake", "Flood", "Hurricane", "Tornado", "Wildfire", "Brazil", "China", "India", "Indonesia", "Japan", "USA"]].values
x_test = test.loc[ : , ["Magnitude", "Fatalities", "Earthquake", "Flood", "Hurricane", "Tornado", "Wildfire", "Brazil", "China", "India", "Indonesia", "Japan", "USA"]].values

#Selecionando o target
y_train = train['Economic_Loss($)'].values
y_test = test['Economic_Loss($)'].values

Gerando os tensores

In [ ]:
import torch

In [ ]:
# preparando e convertendo os dados em tensores, para facilitar calculos e vizualizações

# transformações:         df -> array NumPy | array NumPy -> tensor PyTorch
x_train = torch.tensor(x_train, dtype = torch.float)
x_test  = torch.tensor(x_test,  dtype = torch.float)
y_train = torch.tensor(y_train, dtype = torch.float) # tensor que usaremos como alvo do treinamento
y_test  = torch.tensor(y_test,  dtype = torch.float) # tensor que usaremos para comparar com as previsões do modelo

In [ ]:
x_train.shape # forma do tensor (num_amostras, variaveis_preditoras)
x_train # linhas -> amostras ; colunas -> variável preditora

tensor([[5.7797e+00, 1.8000e+03, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [8.1156e+00, 2.3900e+02, 0.0000e+00,  ..., 0.0000e+00, 1.0000e+00,
         0.0000e+00],
        [7.6800e+00, 9.4380e+03, 0.0000e+00,  ..., 1.0000e+00, 0.0000e+00,
         0.0000e+00],
        ...,
        [8.3999e+00, 4.8300e+02, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [4.8497e+00, 2.2470e+03, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         1.0000e+00],
        [6.7345e+00, 5.4090e+03, 0.0000e+00,  ..., 0.0000e+00, 1.0000e+00,
         0.0000e+00]])

# Normalizando os dados de entrada

Após obtermos essas valore, precisamos **normalizar** os valores das entradas porque eles estão muito altos e posterioremente podem causar problemas. Assim, colocando todos os números no intervalo entre 0 e 1.

In [ ]:
#Maximo e minimo de cada coluna
maximo1 = x_train.max(axis = 0).values
minimo1 = x_train.min(axis = 0).values

maximo2 = x_test.max(axis = 0).values
minimo2 = x_test.min(axis = 0).values

minimo1[0] = 0
minimo2[0] = 0

##Normalizando

x_train = (x_train - minimo1) / (maximo1 - minimo1)
x_test = (x_test - minimo1) / (maximo1 - minimo1)

x_train

tensor([[0.5780, 0.1800, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.8116, 0.0239, 0.0000,  ..., 0.0000, 1.0000, 0.0000],
        [0.7680, 0.9439, 0.0000,  ..., 1.0000, 0.0000, 0.0000],
        ...,
        [0.8400, 0.0483, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.4850, 0.2247, 0.0000,  ..., 0.0000, 0.0000, 1.0000],
        [0.6735, 0.5410, 0.0000,  ..., 0.0000, 1.0000, 0.0000]])

In [ ]:
x_test

tensor([[0.6650, 0.2233, 0.0000,  ..., 1.0000, 0.0000, 0.0000],
        [0.7918, 0.0776, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.2717, 0.3534, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.5526, 0.5053, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.9213, 0.9600, 0.0000,  ..., 0.0000, 1.0000, 0.0000],
        [0.6825, 0.0673, 1.0000,  ..., 1.0000, 0.0000, 0.0000]])

# Configurando a rede neural com funções do PyTorch.

Nossa rede neural tem 3 camadas lineares e função de ativação ReLU

*   Nossa primeira camada gera 16 neurônios
*   A segunda camada gera 8 neurônios
*   A camada oculta (self.output_layer) recebe os 8 neurônios e produz o número de saída definido em output_size
*   Então, nossa função de ativação ReLU introduz a não-linearidade

In [ ]:
import torch.nn as nn

#model = torch.nn.Sequential(
   # torch.nn.Linear(13, 16),
   # torch.nn.ReLU(),
   # torch.nn.Linear(16, 8),
  #  torch.nn.ReLU(),
  #  torch.nn.Linear(8, 1)
#)

class NeuralNewtwork(nn.Module):
  def __init__(self, input_size, output_size):
    super(NeuralNewtwork, self).__init__()
    self.input_layer = nn.Linear(input_size, 16)
    self.hidden_layer1 = nn.Linear(16, 8)
    self.output_layer = nn.Linear(8, output_size)
    self.relu = nn.ReLU()


  def forward(self, x):
    out = self.relu(self.input_layer(x)) # passa pela camada de entrada e aplica ReLU
    out = self.relu(self.hidden_layer1(out)) # passa pela camada oculta e aplica ReLU
    out = self.output_layer(out) # saída final
    return out

# Iniciando o modelo e passando os parametros com as dimensões do dataset

In [ ]:
input_size = 13 # variáveis preditoras
output_size = 1 # variáveis de saída
model = NeuralNewtwork(input_size, output_size)

In [ ]:
## Função de custo
loss_fn = torch.nn.MSELoss()

# Treinando com MiniBatches

In [ ]:
#learning_rate = 0.5 ##1e-6
optimizer = torch.optim.Adam(model.parameters(), lr=0.05)

#Treinando
epochs = 1000

#Configurando os minibatches
batch_size = 100
batch_no = len(x_train) // batch_size

for epoch in range(epochs):
  #Cria minibatches
  for i in range(batch_no):
    start = i * batch_size
    end = start + batch_size

    x_var = x_train[start:end]
    y_var = y_train[start:end]

    #Limpando os gradientes do ultimo uso de loss.backward()
    optimizer.zero_grad()

    #Passo forward
    output_train = model(x_var)

    #Computando a loss
    loss = loss_fn(output_train, y_var)

    if (epoch % (epochs / 10) == 0 and i == 0) :
      print(epoch, loss.item()/ 1e+18)

    #calculando os gradientes
    loss.backward()

    #Atualizando os parametros
    optimizer.step()

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([100])) that is different to the input size (torch.Size([100, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

0 0.3739979181153321
100 0.08805960280073831
200 0.08706032711971635
300 0.08689296083412583
400 0.08686342004906393
500 0.086856702720213
600 0.08685483870440652
700 0.08685428894859264
800 0.08685412573983539
900 0.08685406561029325

In [ ]:
model(x_test)

tensor([[5.0480e+08],
        [5.0417e+08],
        [5.0357e+08],
        ...,
        [5.0487e+08],
        [5.0516e+08],
        [5.0500e+08]], grad_fn=<AddmmBackward0>)

In [ ]:
y_test

tensor([5.5384e+08, 6.4493e+08, 5.7447e+08,  ..., 8.4673e+08, 2.5430e+06,
        8.3308e+08])

In [ ]:
y_pred = model(x_test) - y_test / 1e+8
y_pred
#tirar a o 10^8
#abs

tensor([[5.0480e+08, 5.0480e+08, 5.0480e+08,  ..., 5.0480e+08, 5.0480e+08,
         5.0480e+08],
        [5.0417e+08, 5.0417e+08, 5.0417e+08,  ..., 5.0417e+08, 5.0417e+08,
         5.0417e+08],
        [5.0357e+08, 5.0357e+08, 5.0357e+08,  ..., 5.0357e+08, 5.0357e+08,
         5.0357e+08],
        ...,
        [5.0487e+08, 5.0487e+08, 5.0487e+08,  ..., 5.0487e+08, 5.0487e+08,
         5.0487e+08],
        [5.0516e+08, 5.0516e+08, 5.0516e+08,  ..., 5.0516e+08, 5.0516e+08,
         5.0516e+08],
        [5.0500e+08, 5.0500e+08, 5.0500e+08,  ..., 5.0500e+08, 5.0500e+08,
         5.0500e+08]], grad_fn=<SubBackward0>)

In [ ]:
tensor_abs = torch.abs(y_pred)
tensor_abs

tensor([[5.0480e+08, 5.0480e+08, 5.0480e+08,  ..., 5.0480e+08, 5.0480e+08,
         5.0480e+08],
        [5.0417e+08, 5.0417e+08, 5.0417e+08,  ..., 5.0417e+08, 5.0417e+08,
         5.0417e+08],
        [5.0357e+08, 5.0357e+08, 5.0357e+08,  ..., 5.0357e+08, 5.0357e+08,
         5.0357e+08],
        ...,
        [5.0487e+08, 5.0487e+08, 5.0487e+08,  ..., 5.0487e+08, 5.0487e+08,
         5.0487e+08],
        [5.0516e+08, 5.0516e+08, 5.0516e+08,  ..., 5.0516e+08, 5.0516e+08,
         5.0516e+08],
        [5.0500e+08, 5.0500e+08, 5.0500e+08,  ..., 5.0500e+08, 5.0500e+08,
         5.0500e+08]], grad_fn=<AbsBackward0>)